absolute-paths-allowed-crates = []
absolute-paths-max-segments = 2
accept-comment-above-attributes = true
accept-comment-above-statement = true
allow-comparison-to-zero = true
allow-dbg-in-tests = false
allow-exact-repetitions = true
allow-expect-in-consts = true
allow-expect-in-tests = false
allow-indexing-slicing-in-tests = false
allow-mixed-uninlined-format-args = true
allow-one-hash-in-raw-strings = false
allow-panic-in-tests = false
allow-print-in-tests = false
allow-private-module-inception = false
allow-renamed-params-for = ["core::convert::From", "core::convert::TryFrom", "core::str::FromStr"]
allow-unwrap-in-consts = true
allow-unwrap-in-tests = false
allow-useless-vec-in-tests = false
allowed-dotfiles = []
allowed-duplicate-crates = []
allowed-idents-below-min-chars = ["i", "j", "x", "y", "z", "w", "n"]
allowed-prefixes = ["to", "as", "into", "from", "try_into", "try_from"]
allowed-scripts = ["Latin"]
allowed-wildcard-imports = []
arithmetic-side-effects-allowed = []
arithmetic-side-effects-allowed-binary = []
arithmetic-side-effects-allowed-unary = []
array-size-threshold = 16384
avoid-breaking-exported-api = true
await-holding-invalid-types = []
cargo-ignore-publish = false
check-incompatible-msrv-in-tests = false
check-inconsistent-struct-field-initializers = false
check-private-items = false
cognitive-complexity-threshold = 25
disallowed-macros = []
disallowed-methods = []
disallowed-names = ["foo", "baz", "quux"]
disallowed-types = []
doc-valid-idents = ["KiB", "MiB", "GiB", "TiB", "PiB", "EiB", "MHz", "GHz", "THz", "AccessKit", "CoAP", "CoreFoundation", "CoreGraphics", "CoreText", "DevOps", "Direct2D", "Direct3D", "DirectWrite", "DirectX", "ECMAScript", "GPLv2", "GPLv3", "GitHub", "GitLab", "IPv4", "IPv6", "ClojureScript", "CoffeeScript", "JavaScript", "PostScript", "PureScript", "TypeScript", "WebAssembly", "NaN", "NaNs", "OAuth", "GraphQL", "OCaml", "OpenAL", "OpenDNS", "OpenGL", "OpenMP", "OpenSSH", "OpenSSL", "OpenStreetMap", "OpenTelemetry", "OpenType", "WebGL", "WebGL2", "WebGPU", "WebRTC", "WebSocket", "WebTransport", "WebP", "OpenExr", "YCbCr", "sRGB", "TensorFlow", "TrueType", "iOS", "macOS", "FreeBSD", "NetBSD", "OpenBSD", "TeX", "LaTeX", "BibTeX", "BibLaTeX", "MinGW", "CamelCase"]
enable-raw-pointer-heuristic-for-send = true
enforce-iter-loop-reborrow = false
enforced-import-renames = []
enum-variant-name-threshold = 3
enum-variant-size-threshold = 200
excessive-nesting-threshold = 0
future-size-threshold = 16384
ignore-interior-mutability = ["bytes::Bytes"]
large-error-threshold = 128
lint-commented-code = false
literal-representation-threshold = 16384
matches-for-let-else = "WellKnownTypes"
max-fn-params-bools = 3
max-include-file-size = 1000000
max-struct-bools = 3
max-suggested-slice-pattern-length = 3
max-trait-bounds = 3
min-ident-chars-threshold = 1
missing-docs-allow-unused = false
missing-docs-in-crate-items = false
module-item-order-groupings = [["modules", ["extern_crate", "mod", "foreign_mod"]], ["use", ["use"]], ["macros", ["macro"]], ["global_asm", ["global_asm"]], ["UPPER_SNAKE_CASE", ["static", "const"]], ["PascalCase", ["ty_alias", "enum", "struct", "union", "trait", "trait_alias", "impl"]], ["lower_snake_case", ["fn"]]]
module-items-ordered-within-groupings = "none"
# msrv = current version
pass-by-value-size-limit = 256
pub-underscore-fields-behavior = "PubliclyExported"
semicolon-inside-block-ignore-singleline = false
semicolon-outside-block-ignore-multiline = false
single-char-binding-names-threshold = 4
source-item-ordering = ["enum", "impl", "module", "struct", "trait"]
stack-size-threshold = 512000
standard-macro-braces = []
struct-field-name-threshold = 3
suppress-restriction-lint-in-const = false
too-large-for-stack = 200
too-many-arguments-threshold = 7
too-many-lines-threshold = 100
trait-assoc-item-kinds-order = ["const", "type", "fn"]
# trivial-copy-size-limit = target_pointer_width
type-complexity-threshold = 250
unnecessary-box-size = 128
unreadable-literal-lint-fractions = true
upper-case-acronyms-aggressive = false
vec-box-size-threshold = 4096
verbose-bit-mask-threshold = 1
warn-on-all-wildcard-imports = false
warn-unsafe-macro-metavars-in-private-macros = false
