name: Rust
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always
jobs:

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check style
        run: cargo fmt --all -- --check

      - name: Check with `cargo check`
        run: cargo check --workspace --all-features --all-targets

      - name: Check with Clippy
        run: cargo clippy --workspace --all-features --all-targets  -- --deny warnings

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --workspace --all-features --all-targets --verbose

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: cargo test --workspace --all-features --all-targets --verbose
