name: Rust
on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always
jobs:

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check style
        run: cargo fmt --all -- --check

      - name: Check with `cargo check`
        run: cargo check --workspace --all-features --all-targets

      - name: Check with Clippy
        run: cargo clippy --workspace --all-features --all-targets  -- --deny warnings

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --workspace --all-features --all-targets --verbose

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: cargo test --workspace --all-features --all-targets --verbose

  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4

      - name: Extract tag name
        id: tag_name
        run: echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Check if dry-run is needed
        id: check_dry_run
        run: |
          if [[ "${{ env.tag_name }}" == *"-dry-run" ]]; then
            echo "run_mode=--dry-run" >> $GITHUB_ENV
          else
            echo "run_mode=" >> $GITHUB_ENV

      - name: Cargo Publish
        run: cargo publish ${{ env.run_mode }} -p cataliser
